# Generated by Django 4.2.27 on 2026-01-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='daily_rate',
            field=models.PositiveIntegerField(default=0, help_text='Tarif journalier en euros'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
