# Generated by Antigravity to fix JSONField mismatch

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candidateprofile_daily_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='software_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='mission',
            name='software_required',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
